### ISSUE TITLE
Create Prototype for Job Seeker

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#1]
As an authenticated or non-authenticated Job Seeker, I want to see the job seeker landing page so that I can see a link and teaser to register as a member (location-TBD), a keyword search and list of all current job opportunities in the main content area, a "Job Spotlight" area listing 1 or more jobs in a job carousel, and advertising on the right side.

Reference to current page:
https://careercenter.srainternational.org/fb/index.cfm?fuseaction=seekers.viewGateway

Acceptance Criteria:
- Contains breadcrumbs "Home"
- Contains text and a link to become a member in main content area
- Has a keyword search in main content area
- Displays all current job opportunities, including featured jobs in main content area
- Featured jobs are highlighted and displayed more prominently in main content area
- Contains a Job Spotlight area with ability to carousel multiple job posts in right nav content area
- Displays ad space in right nav content area

Definition of Done:
- [ ] Development complete
- [ ] Approved Internally
- [ ] Approved by SRA

**Comment by thomaspcleary** [comment]
What about the Job Seekers landing page just display the featured jobs?  This would give incentive to pay for the featured job listing.

**Comment by epkatz225** [comment]
Then would the job seeker think that there are only those jobs that are featured?  So being a featured job means that it's the one that shows first and then the user needs to hit show more jobs?

**Comment by thomaspcleary** [comment]
Yes -  a featured job means that it's the one that shows initially on the job seekers screen before a search is performed.  Thoughts?

**Comment by epkatz225** [comment]
I wrote that before we chatted.  I will set that up tonight.
