### ISSUE TITLE
Create prototype for Employers > View Job Posts > View Payment/Invoice

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#18]
Current Invoice (Sent via email only):
[original_msg.txt](https://github.com/thomaspcleary/careercenter/files/1644176/original_msg.txt)

**Comment by epkatz225** [comment]
@thomaspcleary What do you think the Invoices SHOULD entail?  If currently it's just an email, would it be safe to assume that a table would suffice... something similar to attached.
![employers-post-login](https://user-images.githubusercontent.com/35513796/36069965-012518f4-0ec0-11e8-821e-f0150f13893b.png)

**Comment by epkatz225** [comment]
![invoice-modal](https://user-images.githubusercontent.com/35513796/36070196-0689e9c4-0ec4-11e8-9fec-66e28d79e663.png)
![invoices-list](https://user-images.githubusercontent.com/35513796/36070194-03f828b0-0ec4-11e8-9ad8-33d58efead7a.png)

**Comment by epkatz225** [comment]
![invoices-list](https://user-images.githubusercontent.com/35513796/36070200-161851a0-0ec4-11e8-813b-cb80701b7cd9.png)

**Comment by epkatz225** [comment]
![invoice-modal](https://user-images.githubusercontent.com/35513796/36070201-1c63920e-0ec4-11e8-9ac7-adffe0a0b26d.png)
