### ISSUE TITLE
Create Job Seeker Layout

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#19]
As a page within the Job Seekers section, I want to see a layout with breadcrumbs appearing under the header, a main content area, a "Job Spotlight" area listing 1 or more jobs in a job carousel, and advertising on the right side.

NOTE: Though most of the traffic to the career center is job seekers looking for jobs, the employers are what drives revenue.  We need to keep in mind the user experience for employers when designing the Job Seeker area.

Acceptance Criteria:
- Contains breadcrumbs ie.) "Home > Jobs Search"
- Contains a Job Spotlight area with ability to carousel multiple job posts in right nav content area
- Displays ad space in right nav content area under Job Spotlight
- A link to employers section/area

**Comment by epkatz225** [comment]
![job-list](https://user-images.githubusercontent.com/35513796/36069933-8d01dd22-0ebf-11e8-96cc-44b45d017063.png)
![job-list-advanced](https://user-images.githubusercontent.com/35513796/36069934-903bfee6-0ebf-11e8-997f-450056619676.png)
