### ISSUE TITLE
Create Employer Layout

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#20]
As a page within the Employers section, I want to see a layout with breadcrumbs appearing under the header, a main content area, and an advertising slot on the right side.

Acceptance Criteria:
- Contains breadcrumbs ie.) "Home > Employers > Resume Search"

**Comment by epkatz225** [comment]
What term would the Employer search for to find a specific resume?  How would the search results appear or choose the resume?  ... with a specific key word highlighted?

**Comment by thomaspcleary** [comment]
Don't worry about highlighting the actual keyword - currently it searches the title and description fields

**Comment by thomaspcleary** [comment]
Note - we dropped the ad space in the right nav

**Comment by epkatz225** [comment]
![employers-pre-login](https://user-images.githubusercontent.com/35513796/36069909-1ded994e-0ebf-11e8-8917-b68dc9933d93.png)
![employers-post-login](https://user-images.githubusercontent.com/35513796/36069911-2162e7aa-0ebf-11e8-83c1-428d74ad1f40.png)
