### ISSUE TITLE
Create prototype for Pricing

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#7]
As an authenticated or un-authenticated user, I want to go to a pricing page so that I can view member and non-member pricing.

Reference to current page:
https://careercenter.srainternational.org/fb/index.cfm?fuseaction=careerCenter.viewFees

Acceptance Criteria:

Definition of Done:

- [ ] Development complete
- [ ] Approved Internally
- [ ] Approved by SRA

**Comment by thomaspcleary** [comment]
As an authenticated Job Seeker, 

Reference to current page:
https://careercenter.srainternational.org/fb/index.cfm?fuseaction=resumes.viewResumeForm
Acceptance Criteria:
As an authenticated or un-authenticated user, I want to go to a pricing page so that I can view member and non-member pricing.

Definition of Done:

- [ ] Development complete
- [ ] Approved Internally
- [ ] Approved by SRA

**Comment by epkatz225** [comment]
These can be improved, but this is a quick starting point.

![image](https://user-images.githubusercontent.com/35513796/35078495-836be75a-fbd0-11e7-820c-981de9b53c0d.png)

![image](https://user-images.githubusercontent.com/35513796/35078509-90c8209e-fbd0-11e7-881f-85bf02f742d4.png)

**Comment by thomaspcleary** [comment]
Content change - We will only have member and non-member pricing.  $350 for members, $500 for non-members.  I'm thinking we can pull these from the DB, giving them ability to set price and content for the pricing.  I want them to be able to advertise/offer discount codes on this page.  What are your thoughts?  I am trying to keep the implementation simple, so maybe the price isn't dynamic, but we offer dynamic content for promotional offerings?
