### ISSUE TITLE
Create prototype for Login

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#9]
As an un-authenticated user, I want to go to click on login so that I can view a login page, enter my Avectra username and password, and login.

Reference to current page:
https://careercenter.srainternational.org/fb/index.cfm?fuseaction=careerCenter.viewLogin

Acceptance Criteria:

Definition of Done:

- [ ] Development complete
- [ ] Approved Internally
- [ ] Approved by SRA

**Comment by epkatz225** [comment]
@thomaspcleary 
![image](https://user-images.githubusercontent.com/35513796/35080727-6e7a2ef8-fbdd-11e7-8e1a-509195f4b0a4.png)

![image](https://user-images.githubusercontent.com/35513796/35080742-810ce344-fbdd-11e7-8917-219317a67fa2.png)

![image](https://user-images.githubusercontent.com/35513796/35080755-9391c412-fbdd-11e7-8806-9071320bdef7.png)
